import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import Navigation from './leftNav'; // Import the Navigation component

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Floor Management App',
  description: 'Generated by Hasini',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="flex h-screen">
          <nav className="bg-gray-200 p-4">
            <Navigation />
          </nav>
          <div className="flex flex-col flex-1">
            <header className="bg-gray-800 text-white p-4 text-center text-xl">
              Floor Management
            </header>
            <main className="flex-1 p-4">{children}</main>
          </div>
        </div>
      </body>
    </html>
  );
}
